---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: '{{ fromConfigMap "open-cluster-management-observability" "thanos-s3" "BUCKET_NAME" | toLiteral }}'
      endpoint: s3.openshift-storage.svc
      insecure: false
      access_key: '{{ fromSecret "open-cluster-management-observability" "thanos-s3" "AWS_ACCESS_KEY_ID" | base64dec | toLiteral }}'
      secret_key: '{{ fromSecret "open-cluster-management-observability" "thanos-s3" "AWS_SECRET_ACCESS_KEY" | base64dec | toLiteral }}'
      http_config:
        tls_config:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
