apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: custom-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    asdfasdfasdfasd
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhel8"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/rhel8"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rh-sso-7"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/rh-sso-7"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhacm2"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/rhacm2"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift4"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/odf4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/odf4"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/multicluster-engine"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/multicluster-engine"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift-gitops-1"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift-gitops-1"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift-logging"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift-logging"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhceph"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/rhceph"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-release"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift/release-images"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift"
    [[registry.mirror]]
      location = "registry.example:443/ocp4-release/openshift/release"
    [[registry.mirror]]
      location = "mn-ran-ocp-release-local.artifactory-espoo2.int.net.nokia.com:443/ocp4-release/openshift"

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: assisted-service-config
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.ci.openshift.org,registry.redhat.io"
#  DISABLED_HOST_VALIDATIONS: sufficient-packet-loss-requirement-for-role
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    unsupported.agent-install.openshift.io/assisted-service-configmap: 'assisted-service-config'
  name: agent
  namespace: multicluster-engine
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: ocs-storagecluster-cephfs
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-cephfs
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: ocs-storagecluster-cephfs
  mirrorRegistryRef:
    name: custom-registries
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: "4.16"
    rootFSUrl: http://10.16.35.3/redhat/rhcos-live-rootfs.x86_64.img
    url: http://10.16.35.3/redhat/rhcos-live.x86_64.iso
    version: 416.94.202406172220-0
