---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  labels:
    config.nokia.com/included_within: ocp-4.16.15-nokia.24.10.3
    config.nokia.com/reboot: not_required
  name: local-block
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - master0.example.com
        - master1.example.com
        - master2.example.com
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-path/pci-0000:18:00.0-nvme-1
    storageClassName: localblock
    volumeMode: Block

