---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: observability-secret
  namespace: local-policies
spec:
  remediationAction: inform
  sourceFiles:
    - fileName: thanos-s3-secret.yaml
      policyName: w10
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "1"
  bindingRules:
    name: local-cluster
  bindingExcludedRules: {}

